/**
 * Módulo de Pacientes (CRM)
 */
const Patients = {
    STORAGE_KEY: 'medicare_patients',
    patients: [],

    init() {
        this.patients = Storage.get(this.STORAGE_KEY);
        this.cacheDOM();
        this.bindEvents();
        this.renderTable();
        // Inicializar el select de pacientes en el formulario de citas
        if (typeof Appointments !== 'undefined') {
            Appointments.updatePatientSelect();
        }
    },

    cacheDOM() {
        this.btnNew = document.getElementById('btn-new-patient');
        this.btnCancel = document.getElementById('btn-cancel-patient');
        this.form = document.getElementById('patient-form');
        this.tbody = document.getElementById('patients-tbody');
        this.formTitle = document.getElementById('patient-form-title');
    },

    bindEvents() {
        this.btnNew.addEventListener('click', () => {
            this.formTitle.textContent = 'Registrar Nuevo Paciente';
            UI.clearForm('patient-form');
            UI.toggleForm('patient-form-container', true);
            const now = new Date();
            document.getElementById('patient-date').value = now.toISOString().split('T')[0];
        });

        this.btnCancel.addEventListener('click', () => {
            UI.toggleForm('patient-form-container', false);
        });

        this.form.addEventListener('submit', (e) => {
            e.preventDefault();
            this.savePatient();
        });
    },

    savePatient() {
        const idInput = document.getElementById('patient-id').value;
        const patientData = {
            name: document.getElementById('patient-name').value,
            age: document.getElementById('patient-age').value,
            phone: document.getElementById('patient-phone').value,
            email: document.getElementById('patient-email').value,
            date: document.getElementById('patient-date').value,
            history: document.getElementById('patient-history').value
        };

        // Leer opción de agendado (aplica para nuevos y existentes)
        const isAgendar = document.getElementById('opt-agendar').checked;

        if (idInput) {
            // Editar existente
            const index = this.patients.findIndex(p => p.id === idInput);
            if (index !== -1) {
                this.patients[index] = { ...this.patients[index], ...patientData };
                
                // Manejo de la cita al editar
                if (typeof Appointments !== 'undefined') {
                    const existingAppIndex = Appointments.appointments.findIndex(a => a.patientId === idInput && a.isAutoGenerated);
                    const hasAnyApp = Appointments.appointments.some(a => a.patientId === idInput);

                    if (isAgendar && !hasAnyApp) {
                        // El usuario cambió a "Sí, agendar" y no tenía citas -> creamos una
                        const now = new Date();
                        const autoAppointment = {
                            id: Storage.generateId(),
                            patientId: idInput,
                            date: patientData.date || now.toISOString().split('T')[0],
                            time: now.toTimeString().slice(0, 5),
                            status: 'Pendiente',
                            totalCost: 0,
                            paidAmount: 0,
                            reason: patientData.history.trim() || 'Primera cita',
                            isAutoGenerated: true
                        };
                        Appointments.appointments.push(autoAppointment);
                        Storage.set(Appointments.STORAGE_KEY, Appointments.appointments);
                        alert('Paciente actualizado. ✅ Cita agendada automáticamente.');
                    } else if (!isAgendar && existingAppIndex !== -1) {
                        // El usuario cambió a "No agendar" y tenía la cita autogenerada -> la eliminamos
                        Appointments.appointments.splice(existingAppIndex, 1);
                        Storage.set(Appointments.STORAGE_KEY, Appointments.appointments);
                        alert('Paciente actualizado. ❌ Cita agendada eliminada.');
                    } else {
                        alert('Paciente actualizado correctamente.');
                    }
                } else {
                    alert('Paciente actualizado correctamente.');
                }
            }
        } else {
            // Crear nuevo
            patientData.id = Storage.generateId();
            this.patients.push(patientData);

            if (isAgendar && typeof Appointments !== 'undefined') {
                // Crear cita automática en estado "Pendiente" → badge "Agendada"
                const now = new Date();
                const autoAppointment = {
                    id: Storage.generateId(),
                    patientId: patientData.id,
                    date: patientData.date || now.toISOString().split('T')[0],
                    time: now.toTimeString().slice(0, 5),
                    status: 'Pendiente',
                    totalCost: 0,
                    paidAmount: 0,
                    reason: patientData.history.trim() || 'Primera cita',
                    isAutoGenerated: true
                };
                Appointments.appointments.push(autoAppointment);
                Storage.set(Appointments.STORAGE_KEY, Appointments.appointments);
                alert('Paciente registrado. ✅ Cita agendada automáticamente.');
            } else {
                alert('Paciente registrado sin cita agendada.');
            }
        }

        Storage.set(this.STORAGE_KEY, this.patients);
        UI.toggleForm('patient-form-container', false);
        UI.clearForm('patient-form');

        // Refrescar agenda y select de pacientes
        if (typeof Appointments !== 'undefined') {
            Appointments.renderTable();
            Appointments.updatePatientSelect();
        }

        // Refrescar tabla de pacientes
        this.renderTable();
    },


    editPatient(id) {
        const patient = this.patients.find(p => p.id === id);
        if (!patient) return;

        document.getElementById('patient-id').value = patient.id;
        document.getElementById('patient-name').value = patient.name;
        document.getElementById('patient-age').value = patient.age;
        document.getElementById('patient-phone').value = patient.phone;
        document.getElementById('patient-email').value = patient.email || '';
        document.getElementById('patient-date').value = patient.date || '';
        document.getElementById('patient-history').value = patient.history || '';

        this.formTitle.textContent = 'Editar Paciente';
        
        // Ajustar el toggle de agendado según las citas del paciente
        if (typeof Appointments !== 'undefined') {
            const hasAppointments = Appointments.appointments.some(a => a.patientId === id);
            if (hasAppointments) {
                document.getElementById('opt-agendar').checked = true;
            } else {
                document.getElementById('opt-no-agendar').checked = true;
            }
        }

        UI.toggleForm('patient-form-container', true);
        window.scrollTo(0, 0);
    },

    deletePatient(id) {
        if (confirm('¿Está seguro de eliminar este paciente? Esto no eliminará sus citas.')) {
            this.patients = this.patients.filter(p => p.id !== id);
            Storage.set(this.STORAGE_KEY, this.patients);
            this.renderTable();
            if (typeof Appointments !== 'undefined') {
                Appointments.updatePatientSelect();
            }
        }
    },

    renderTable() {
        this.tbody.innerHTML = '';
        
        if (this.patients.length === 0) {
            this.tbody.innerHTML = '<tr><td colspan="5" style="text-align:center;">No hay pacientes registrados</td></tr>';
            return;
        }

        this.patients.forEach(patient => {
            let total = 0;
            let paid = 0;
            let hasAppointments = false;

            // Sumar los costos y pagos de sus citas
            if (typeof Appointments !== 'undefined') {
                const appointments = Appointments.appointments.filter(a => a.patientId === patient.id);
                if (appointments.length > 0) hasAppointments = true;
                
                appointments.forEach(app => {
                    total += parseFloat(app.totalCost) || 0;
                    paid  += parseFloat(app.paidAmount) || 0;
                });
            }

            let appointmentStatus = 'Sin Cita';
            let badgeClass = 'status-sincita';

            if (typeof Appointments !== 'undefined') {
                const appointments = Appointments.appointments.filter(a => a.patientId === patient.id);
                if (appointments.length > 0) {
                    const hasPending   = appointments.some(a => a.status === 'Pendiente');
                    const hasCompleted = appointments.some(a => a.status === 'Completada');
                    const hasCancelled = appointments.some(a => a.status === 'Cancelada');

                    if (hasPending) {
                        appointmentStatus = 'Cita Agendada';
                        badgeClass = 'status-pendiente';
                    } else if (hasCompleted) {
                        appointmentStatus = 'Completada';
                        badgeClass = 'status-completada';
                    } else if (hasCancelled) {
                        appointmentStatus = 'Cancelada';
                        badgeClass = 'status-cancelada';
                    }
                }
            }

            const tr = document.createElement('tr');
            tr.innerHTML = `
                <td><strong>${patient.name}</strong><br><small>${patient.email || ''}</small></td>
                <td>${patient.date || ''}</td>
                <td>${patient.phone}</td>
                <td><span class="status-badge ${badgeClass}">${appointmentStatus}</span></td>
                <td>
                    <button class="btn btn-edit" onclick="Patients.editPatient('${patient.id}')">✏️ Editar</button>
                    <button class="btn btn-danger" onclick="Patients.deletePatient('${patient.id}')">🗑️ Eliminar</button>
                </td>
            `;
            this.tbody.appendChild(tr);
        });
    },

    // Para uso externo (ej. por Appointments)
    getPatientsList() {
        return this.patients;
    },
    
    getPatientName(id) {
        const patient = this.patients.find(p => p.id === id);
        return patient ? patient.name : 'Paciente Desconocido';
    }
};
